apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.peerport }}
      name: peerport
    - port: {{ .Values.service.leaderport }}
      name: leaderport
    - port: {{ .Values.service.clientport }}
      name: clientport
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}


