---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoo2
  name: zoo2
spec:
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zoo2
status:
  loadBalancer: {}
